
AVW_ATTRIBUTE_DE: tuple[str] = (
    "ID",
    "Dokument-ID",
    "Basis für Testdesign",
    "Typ",
    "Kategorie",
    "Status",
    "Feature",
    "Reifegrad",
    "Umsetzer",
    "ASIL",
    "BSM-SaFuSi Bewertung",
    "BSM-ZZ Bewertung",
    "BSM-ED Bewertung",
    "BSM-FFF Bewertung",
    "BSM-O Bewertung",
    "BSM-Se Bewertung",
    "MV",
    "Cluster Testing",
    "Dokument",
    "Kommentar Redaktionskreis",
    "temp1_Text",
    "Anforderungsverantwortliche",
    "Abgezweigt aus",
)